# Simple workflow for deploying static content to GitHub Pages
name: Deploy - Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["master"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout - Repo
        uses: actions/checkout@v3

      - name: Setup - Node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Setup - Pages
        uses: actions/configure-pages@v1

      - name: Setup - npmrc
        run: echo "//npm.pkg.github.com/:_authToken=${{secrets.GH_TOKEN}}" >> .npmrc

      - name: Install & Build - App
        run: |
          yarn install
          yarn build:widget

      - name: Upload - Artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: "./build"

      - name: Deploy - GitHub Pages
        id: deployment
        uses: actions/deploy-pages@main
